version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: back
      SPRING_DATASOURCE_URL: jdbc:postgresql://db.uaejumcmdpdyhvecjles.supabase.co:5432/postgres?user=postgres&password=zkvrtrPNmHnsUZn7
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: UZQvKtQseNYc9Tvx
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver